- hosts: kube_control_plane[0]
  become: true
  tasks: 
     - name: Use fetch module for this task  
       fetch:
          src: /root/.kube/config
          dest: /tmp/config
          flat: yes
          
- hosts: node1
  become: true
- name: Create a directory if it does not exist
  ansible.builtin.file:
    path: /root/.kube
    state: directory
    mode: '0755'

- hosts: node1
  become: true
  tasks:
     - name: Copy files
       copy:
         src: /tmp/config
         dest: /root/.kube/config

- hosts: node1 
  become: true
  tasks: 
     - name: replace server in kubeconfig
       lineinfile:
         path: /root/.kube/config
         regexp: "    server: https://lb-apiserver.kubernetes.local:6443"
         line:  "    server: https://{{ hostvars[groups['kube_control_plane'][0]].ansible_host }}:6443"
         backrefs: yes

- hosts: kube_control_plane, kube_node
  become: true
  tasks:
     - name:  Install NFS client package
       apt:
         name:  nfs-common
         state: present
         update_cache: true 
