- name: Import vars
  run_once: true
  include_vars:
    file: inventory/local/cluster-variable.yaml
    name: vardata

- name: Copy temp kube config file for helm
  become: true
  copy:
    src: /root/.kube/config
    dest: /tmp/config
    remote_src: true
    mode: '0644'

- name: Create namespace
  kubernetes.core.k8s:
    api_version: v1
    kind: Namespace
    name: my-namespace
    kubeconfig: /tmp/config
    remote_src: true

- name: Install/Upgrade Jarvice Helm chart
  become: true
  kubernetes.core.helm:
    name: jarvice
    chart_ref: jarvice
    chart_repo_url: https://nimbix.github.io/jarvice-helm/
    namespace: jarvice-system
    create_namespace: true
    chart_version: "{{ vardata.jarviceversion }}"
    release_state: present
    values_files:
      - override.yaml
    kubeconfig: /tmp/config

- name: Remove /tmp/config (delete file)
  become: true
  ansible.builtin.file:
    path: /tmp/config
    state: absent


#END
##########################################################################
