- name: Jarvice Install
  become: true
  shell: "{{ item }}"
  with_items:    
    - "kubectl create ns jarvice-system --kubeconfig /root/.kube/config"
    - "helm upgrade jarvice jarvice --version 3.25.1-202503171803 --repo https://nimbix.github.io/jarvice-helm/ --namespace jarvice-system --install --values override.yaml"
  register: command_output


#- name: Create Jarvice namespace
#  become: true
#  kubernetes.core.k8s:
#    name: jarvice-system
#    api_version: v1
#    kind: Namespace
#    state: present
#    kubeconfig: /root/.kube/config

#- name: Deploy Grafana chart on 5.0.12 with values loaded from template
# kubernetes.core.helm:
#    name: jarvice
#    repo_url: "https://nimbix.github.io/jarvice-helm/"
#    release_namespace: jarvice-system
#    chart_version: 3.25.1-202503171803
#    values: "override.yaml"
