---

- name: "2.2.1 | PATCH | Ensure NIS Client is not installed"
  when:
    - ubtu24cis_rule_2_2_1
    - not ubtu24cis_nis_server
  tags:
    - level1-server
    - level1-workstation
    - rule_2.2.1
    - NIST800-53R5_CM-7
    - NIST800-53R5_CM-11
    - nis
  ansible.builtin.package:
    name: nis
    state: absent
    purge: "{{ ubtu24cis_purge_apt }}"

- name: "2.2.2 | PATCH | Ensure rsh client is not installed"
  when:
    - ubtu24cis_rule_2_2_2
    - not ubtu24cis_rsh_client
  tags:
    - level1-server
    - level1-workstation
    - patch
    - rule_2.2.2
    - NIST800-53R5_CM-7
    - rsh
  ansible.builtin.package:
    name: rsh-client
    state: absent
    purge: "{{ ubtu24cis_purge_apt }}"

- name: "2.2.3 | PATCH | Ensure talk client is not installed"
  when:
    - ubtu24cis_rule_2_2_3
    - not ubtu24cis_talk_client
  tags:
    - level1-server
    - level1-workstation
    - patch
    - rule_2.2.3
    - NIST800-53R5_CM-7
    - talk
  ansible.builtin.package:
    name: talk
    state: absent
    purge: "{{ ubtu24cis_purge_apt }}"

- name: "2.2.4 | PATCH | Ensure telnet client is not installed"
  when:
    - ubtu24cis_rule_2_2_4
    - not ubtu24cis_telnet_required
  tags:
    - level1-server
    - level1-workstation
    - patch
    - rule_2.2.4
    - NIST800-53R5_CM-7
    - NIST800-53R5_CM-11
    - telnet
  ansible.builtin.package:
    name:
      - telnet
      - inetutils-telnet
    state: absent
    purge: "{{ ubtu24cis_purge_apt }}"

- name: "2.2.5 | PATCH | Ensure ldap client is not installed"
  when:
    - ubtu24cis_rule_2_2_5
    - not ubtu24cis_ldap_clients_required
  tags:
    - level1-server
    - level1-workstation
    - patch
    - rule_2.2.5
    - NIST800-53R5_CM-7
    - ldap
  ansible.builtin.package:
    name: ldap-utils
    state: absent
    purge: "{{ ubtu24cis_purge_apt }}"

- name: "2.2.6 | PATCH | Ensure ftp is not installed"
  when:
    - ubtu24cis_rule_2_2_6
    - not ubtu24cis_ftp_client
  tags:
    - level1-server
    - level1-workstation
    - patch
    - rule_2.2.6
    - NIST800-53R5_CM-7
    - NIST800-53R5_CM-11
    - ftp
  ansible.builtin.package:
    name:
      - ftp
      - tnftp
    state: absent
    purge: "{{ ubtu24cis_purge_apt }}"
