- name: time synch...for when restoring from snap
  become: true
  shell: "{{ item }}"
  with_items:    
    - "date -s \"$(wget -qSO- --max-redirect=0 google.com 2>&1 | grep Date: | cut -d' ' -f5-8)Z\""
  register: command_output


- name: system parameters for K8s initiate
  become: true
  shell: "{{ item }}"
  with_items:
          - "swapoff -a"
          - "sed -e '/swap/ s/^#*/#/' -i /etc/fstab"
          - "systemctl mask swap.target"
          - "sysctl -w net.ipv6.conf.all.disable_ipv6=1"
          - "sed -i '/ swap / s/^\\(.*\\)$/#\\1/g' /etc/fstab"
          - "printf '%s\\n' 'overlay' 'br_netfilter' >/etc/modules-load.d/containerd.conf"
          - "modprobe overlay"
          - "modprobe br_netfilter"
          - "printf '%s\\n' 'net.bridge.bridge-nf-call-ip6tables = 1' 'net.bridge.bridge-nf-call-iptables = 1' 'net.ipv4.ip_forward = 1' >/etc/sysctl.d/kubernetes.conf"
          - "sysctl --system"
          - "printf '%s\\n' 'KUBELET_EXTRA_ARGS=\"--cgroup-driver=cgroupfs\"'  >/etc/default/kubelet"
          - "systemctl daemon-reload && sudo systemctl restart kubelet"
