apiVersion: apps/v1
kind: Deployment
metadata:
  name: coredns
  namespace: kube-system
spec:
  template:
    spec:
      tolerations:
      - effect: NoSchedule
        key: node-role.jarvice.io/jarvice-system
        operator: Exists