apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: prometheus-grafana
  namespace: prometheus-stack
spec:
  tolerations:
  - effect: NoSchedule
    key: node-role.jarvice.io/jarvice-system
    operator: Exists
