apiVersion: apps/v1
kind: Deployment
metadata:
  name: prometheus-kube-prometheus-operator
  namespace: prometheus-stack
spec:
  template:
    spec:
      tolerations:
      - effect: NoSchedule
        key: node-role.jarvice.io/jarvice-system
        operator: Exists