######Set jarvice labels on compute and system nodes################################
- name: Set control plane nodes jarvice labels
  k8s:
    state: patched
    kind: Node
    name: "{{ item }}"
    definition:            
      metadata:
        labels:
          node-role.kubernetes.io/jarvice-system: ""
  with_items: "{{ groups['kube_control_plane'] }}"
  delegate_to: localhost

- name: Set worker nodes jarvice labels
  k8s:
    state: patched
    kind: Node
    name: "{{ item }}"
    definition:            
      metadata:
        labels:
          node-role.kubernetes.io/jarvice-compute: ""
  with_items: "{{ groups['kube_node'] }}"
  delegate_to: localhost

############Apply taints to nodes#################################################
- name: Set control plane nodes jarvice taints
  become: true
  command: "kubectl taint node {{ item }} node-role.jarvice.io/jarvice-system=true:NoSchedule"
  with_items: "{{ groups['kube_control_plane'] }}"
  ignore_errors: true

- name: Set worker nodes jarvice taints
  become: true
  command: "kubectl taint node {{ item }} node-role.jarvice.io/jarvice-compute=true:NoSchedule"
  with_items: "{{ groups['kube_node'] }}"
  ignore_errors: true

- name: Remove control plane taint
  become: true
  command: "kubectl taint node {{ item }} node-role.kubernetes.io/control-plane=true:NoSchedule-"

- name: Apply tolerations to Traefik Deployment
  kubernetes.core.k8s:    
    state: present
    namespace: kube-system
    src: k8spatches/traefikpatch.yaml
    validate_certs: false
  delegate_to: localhost

- name: Apply tolerations to coredns Deployment
  kubernetes.core.k8s:    
    state: present
    namespace: kube-system
    src: k8spatches/corednspatch.yaml
    validate_certs: false
  delegate_to: localhost

- name: Apply tolerations to nfs Deployment
  kubernetes.core.k8s:    
    state: present
    namespace: kube-system
    src: k8spatches/nfspatch.yaml
    validate_certs: false
  delegate_to: localhost

- name: Apply tolerations to metallb Deployment
  kubernetes.core.k8s:    
    state: present
    namespace: metallb-system
    src: k8spatches/metallbpatch.yaml
    validate_certs: false
  delegate_to: localhost

- name: Apply tolerations to cilium Deployment
  kubernetes.core.k8s:    
    state: present
    namespace: kube-system
    src: k8spatches/ciliumpatch.yaml
    validate_certs: false
  delegate_to: localhost

- name: Apply tolerations to prom metrics Deployment
  kubernetes.core.k8s:    
    state: present
    namespace: prometheus-stack
    src: k8spatches/prommetpatch.yaml
    validate_certs: false
  delegate_to: localhost

- name: Apply tolerations to prom operator Deployment
  kubernetes.core.k8s:    
    state: present
    namespace: prometheus-stack
    src: k8spatches/promoppatch.yaml
    validate_certs: false
  delegate_to: localhost

- name: Apply tolerations to grafana Stateful set
  kubernetes.core.k8s:    
    state: present
    namespace: prometheus-stack
    src: k8spatches/grafanapatch.yaml
    validate_certs: false
  delegate_to: localhost
#END###################################################################################################

# - name: Show all the hosts in the inventory
#   ansible.builtin.debug:
#     msg: "{{ item }}"
#   loop: "{{ groups['kube_control_plane'] }}"
#   delegate_to: localhost


# ##############Sets current deployments tolerations###################################################
# - name: Set tolerations on management pods and deployments to run on control planes
#   become: true
#   shell: "{{ item }}"
#   with_items: 
#     - "kubectl rollout restart deployment traefik -n kube-system"
#     - "kubectl patch deployment traefik -n kube-system --type merge --patch-file deploypatch.yaml"
#     - "kubectl rollout restart deployment coredns -n kube-system"
#     - "kubectl patch deployment coredns -n kube-system --type merge --patch-file deploypatch.yaml"
#     - "kubectl rollout restart deployment nfs-subdir-external-provisioner -n kube-system"
#     - "kubectl patch deployment nfs-subdir-external-provisioner --type merge --patch-file deploypatch.yaml -n kube-system"    
#     - "kubectl rollout restart deployment controller -n metallb-system"
#     - "kubectl patch deployment controller -n metallb-system --type merge --patch-file deploypatch.yaml"
#     - "kubectl rollout restart deployment cilium-operator -n kube-system"
#     - "kubectl patch deployment cilium-operator -n kube-system --type merge --patch-file deploypatch.yaml"
#     - "kubectl rollout restart deployment prometheus-kube-state-metrics -n prometheus-stack"
#     - "kubectl patch deployment prometheus-kube-state-metrics -n prometheus-stack --type merge --patch-file deploypatch.yaml"
#     - "kubectl rollout restart deployment prometheus-kube-prometheus-operator -n prometheus-stack"
#     - "kubectl patch deployment prometheus-kube-prometheus-operator -n prometheus-stack --type merge --patch-file deploypatch.yaml"

#     - "kubectl patch statefulset prometheus-grafana --type merge --patch-file deploypatch.yaml -n prometheus-stack"
#     - "kubectl delete pod prometheus-grafana-0 -n prometheus-stack"
#     - "kubectl delete pod loki-0 -n prometheus-stack"
#     - "kubectl delete pod alertmanager-prometheus-kube-prometheus-alertmanager-0 -n prometheus-stack"    
#     - "kubectl delete pod prometheus-prometheus-kube-prometheus-prometheus-0 -n prometheus-stack"
   
    
